# Generated by Django 5.1 on 2024-09-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('imagem', models.ImageField(upload_to='')),
                ('descricao_1', models.TextField()),
                ('descricao_2', models.TextField()),
                ('descricao_3', models.TextField()),
                ('descricao_4', models.TextField()),
                ('descricao_5', models.TextField()),
                ('descricao_6', models.TextField()),
                ('descricao_7', models.TextField()),
            ],
        ),
    ]
