# Generated by Django 5.1 on 2024-09-06 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genero',
            name='imagem',
        ),
    ]
