# Generated by Django 5.1 on 2024-09-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_genero_descricao_1_alter_genero_descricao_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genero',
            name='imagem',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
