# Generated by Django 5.1.2 on 2024-10-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_genero_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, upload_to='')),
                ('titulo', models.CharField(max_length=30)),
                ('descricao', models.TextField(max_length=600)),
            ],
        ),
        migrations.RenameField(
            model_name='genero',
            old_name='nome',
            new_name='titulo',
        ),
    ]
